name: TorchRefill
version: ${project.version}
main: lol.hyper.torchrefill.TorchRefill
api-version: 1.13
author: hyperdefined
website: https://www.spigotmc.org/resources/torchrefill.85609/
description: Automatically put torches into your hand!
commands:
  tr:
    description: Main command.